#!/bin/bash
sudo -i
cd xmrig
cd build
sudo sysctl -w vm.nr_hugepages=128
sudo systemctl start tor
sudo toriptables2.py -l

torify ./xmrig --no-color --donate-level 1 --cpu-priority 5 -o pool.supportxmr.com:9000 -u 42iZdPFRQPN1qpHG6niqkG6cY3oZph9Vn9JZvKZ1Guce7UVWj587z7TJ15fW85FDQHNU9Wiqe3qGXfP2VNHq4xa9MK5LUrU -p x6 -k --tls -t 4 -a cn/r --background
sleep 12m
shutdown -r now
